# Generated by Django 5.0.6 on 2024-06-13 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('room', models.IntegerField()),
                ('square', models.FloatField()),
                ('city', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('description', models.TextField()),
                ('photo', models.URLField()),
                ('star', models.BooleanField()),
                ('focus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat')),
            ],
        ),
    ]
