# Generated by Django 5.0.6 on 2024-06-13 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='myapp.flat'),
        ),
        # migrations.AlterModelTable(
        #     name='flat',
        #     table='flats',
        # ),
        # migrations.AlterModelTable(
        #     name='price',
        #     table='prices',
        # ),
    ]
