# Generated by Django 5.0.6 on 2024-06-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_price_flat_alter_flat_table_alter_price_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat'),
        ),
    ]
