# Generated by Django 5.0.6 on 2024-06-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_price_flat'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='price',
            table=None,
        ),
    ]
