# Generated by Django 5.0.6 on 2024-06-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_flat_table_alter_price_table'),
    ]

    operations = [
        # migrations.AlterModelTable(
        #     name='flat',
        #     table='flats',
        # ),
        # migrations.AlterModelTable(
        #     name='price',
        #     table='prices',
        # ),
    ]
