# Generated by Django 5.0.6 on 2024-06-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_flat_table_alter_price_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Flats',
        ),
        migrations.RenameModel(
            old_name='Price',
            new_name='Pricec',
        ),
    ]
