# Generated by Django 5.0.6 on 2024-06-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_flat_flats_rename_price_pricec'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flats',
            table=None,
        ),
        migrations.AlterModelTable(
            name='pricec',
            table=None,
        ),
    ]
