# Generated by Django 5.0.6 on 2024-06-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_flats_table_alter_pricec_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flats',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pricec',
            options={'managed': False},
        ),
    ]
