# Generated by Django 5.0.6 on 2024-07-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_flats_options_alter_pricec_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='flats',
            table='flats',
        ),
        migrations.AlterModelTable(
            name='pricec',
            table='prices',
        ),
    ]
