# Generated by Django 5.0.6 on 2024-07-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_author_category_city_parser_setfilter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='author',
        ),
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='object',
            name='title',
        ),
        migrations.AddField(
            model_name='object',
            name='photo',
            field=models.URLField(default='No photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='room',
           field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='square',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='url',
            field=models.URLField(default='No URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
