# Generated by Django 5.0.6 on 2024-07-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_object_author_remove_object_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='city',
            field=models.CharField(default='No city', max_length=100),
        ),
        migrations.AlterField(
            model_name='object',
            name='description',
            field=models.TextField(default='No description'),
        ),
        migrations.AlterField(
            model_name='object',
            name='photo',
            field=models.URLField(default='No photo'),
        ),
        migrations.AlterField(
            model_name='object',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='object',
            name='square',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='object',
            name='url',
            field=models.URLField(default='No URL'),
        ),
    ]
